export const MEMBERS = {
  sakurazaka: [
    { en: "Endo Hikari",       ja: "遠藤 光莉",   photo: "endo_hikari" , group: "sakurazaka" },
    { en: "Ozono Rei",         ja: "大園 玲",     photo: "ozono_rei" , group: "sakurazaka" },
    { en: "Onuma Akiho",       ja: "大沼 晶保",   photo: "onuma_akiho" , group: "sakurazaka" },
    { en: "Kousaka Marino",    ja: "幸阪 茉里乃", photo: "kousaka_marino" , group: "sakurazaka" },
    { en: "Takemoto Yui",      ja: "武元 唯衣",   photo: "takemoto_yui" , group: "sakurazaka" },
    { en: "Tamura Hono",       ja: "田村 保乃",   photo: "tamura_hono" , group: "sakurazaka" },
    { en: "Fujiyoshi Karin",   ja: "藤吉 夏鈴",   photo: "fujiyoshi_karin" , group: "sakurazaka" },
    { en: "Masumoto Kira",     ja: "増本 綺良",   photo: "masumoto_kira" , group: "sakurazaka" },
    { en: "Matsuda Rina",      ja: "松田 里奈",   photo: "matsuda_rina" , group: "sakurazaka" },
    { en: "Morita Hikaru",     ja: "森田 ひかる", photo: "morita_hikaru" , group: "sakurazaka" },
    { en: "Moriya Rena",       ja: "守屋 麗奈",   photo: "moriya_rena" , group: "sakurazaka" },
    { en: "Yamazaki Ten",      ja: "山﨑 天",     photo: "yamasaki_ten" , group: "sakurazaka" },
    { en: "Ishimori Rika",     ja: "石森 璃花",   photo: "ishimori_rika" , group: "sakurazaka" },
    { en: "Endo Riko",         ja: "遠藤 理子",   photo: "endo_riko" , group: "sakurazaka" },
    { en: "Odakura Reina",     ja: "小田倉 麗奈", photo: "odakura_reina" , group: "sakurazaka" },
    { en: "Kojima Nagisa",     ja: "小島 凪紗",   photo: "kojima_nagisa" , group: "sakurazaka" },
    { en: "Taniguchi Airi",    ja: "谷口 愛季",   photo: "taniguchi_airi" , group: "sakurazaka" },
    { en: "Nakashima Yuzuki",  ja: "中嶋 優月",   photo: "nakashima_yuzuki" , group: "sakurazaka" },
    { en: "Matono Mio",        ja: "的野 美青",   photo: "matono_mio" , group: "sakurazaka" },
    { en: "Mukai Itoha",       ja: "向井 純葉",   photo: "itoha_mukai" , group: "sakurazaka" },
    { en: "Murai Yu",          ja: "村井 優",     photo: "murai_yu" , group: "sakurazaka" },
    { en: "Murayama Miu",      ja: "村山 美羽",   photo: "murayama_miu" , group: "sakurazaka" },
    { en: "Yamashita Shizuki", ja: "山下 瞳月",   photo: "yamashita_shizuki" , group: "sakurazaka" },
    { en: "Asai Konomi",       ja: "浅井 恋乃未", photo: "asai_konomi" , group: "sakurazaka" },
    { en: "Inaguma Hina",      ja: "稲熊 ひな",   photo: "inaguma_hina" , group: "sakurazaka" },
    { en: "Katsumata Haru",    ja: "勝又 春",     photo: "katsumata_haru" , group: "sakurazaka" },
    { en: "Sato Neo",          ja: "佐藤 愛桜",   photo: "sato_neo" , group: "sakurazaka" },
    { en: "Nakagawa Chihiro",  ja: "中川 智尋",   photo: "nakagawa_chihiro" , group: "sakurazaka" },
    { en: "Matsumoto Wako",    ja: "松本 和子",   photo: "matsumoto_wako" , group: "sakurazaka" },
    { en: "Meguro Hiiro",      ja: "目黒 陽色",   photo: "meguri_hiiro" , group: "sakurazaka" },
    { en: "Yamakawa Ui",       ja: "山川 宇衣",   photo: "yamakawa_ui" , group: "sakurazaka" },
    { en: "Yamada Momomi",     ja: "山田 桃実",   photo: "yamada_momomi" , group: "sakurazaka" },
  ],
  nogizaka: [
    { en: "Ito Riria",                ja: "伊藤 理々杏",        photo: "ito_riria" , group: "nogizaka" },
    { en: "Iwamoto Renka",            ja: "岩本 蓮加",          photo: "iwamoto_renka" , group: "nogizaka" },
    { en: "Yoshida Ayano Christie",   ja: "吉田 綾乃クリスティ", photo: "yoshida_ayano_christie" , group: "nogizaka" },
    { en: "Endo Sakura",              ja: "遠藤 さくら",        photo: "endo_sakura" , group: "nogizaka" },
    { en: "Kaki Haruka",              ja: "賀喜 遥香",          photo: "kaki_haruka" , group: "nogizaka" },
    { en: "Kanagawa Saya",            ja: "金川 紗耶",          photo: "kanagawa_saya" , group: "nogizaka" },
    { en: "Kuromi Haruka",            ja: "黒見 明香",          photo: "kuromi_haruka" , group: "nogizaka" },
    { en: "Shibata Yuna",             ja: "柴田 柚菜",          photo: "shibata_yuna" , group: "nogizaka" },
    { en: "Tamura Mayu",              ja: "田村 真佑",          photo: "tamura_mayu" , group: "nogizaka" },
    { en: "Tsutsui Ayame",            ja: "筒井 あやめ",        photo: "tsutsui_ayame" , group: "nogizaka" },
    { en: "Hayashi Runa",             ja: "林 瑠奈",            photo: "hayashi_runa" , group: "nogizaka" },
    { en: "Yumiki Nao",               ja: "弓木 奈於",          photo: "yumiki_nao" , group: "nogizaka" },
    { en: "Ioki Mao",                 ja: "五百城 茉央",        photo: "ioki_mao" , group: "nogizaka" },
    { en: "Ikeda Teresa",             ja: "池田 瑛紗",          photo: "ikeda_teresa" , group: "nogizaka" },
    { en: "Ichinose Miku",            ja: "一ノ瀬 美空",        photo: "ichinose_miku" , group: "nogizaka" },
    { en: "Inoue Nagi",               ja: "井上 和",            photo: "inoue_nagi" , group: "nogizaka" },
    { en: "Okamoto Hina",             ja: "岡本 姫奈",          photo: "okamoto_hina" , group: "nogizaka" },
    { en: "Ogawa Aya",                ja: "小川 彩",            photo: "ogawa_aya" , group: "nogizaka" },
    { en: "Okuda Iroha",              ja: "奥田 いろは",        photo: "okuda_iroha" , group: "nogizaka" },
    { en: "Kawasaki Sakura",          ja: "川﨑 桜",            photo: "kawasaki_sakura" , group: "nogizaka" },
    { en: "Sugawara Satsuki",         ja: "菅原 咲月",          photo: "sugawara_satsuki" , group: "nogizaka" },
    { en: "Tomisato Nao",             ja: "冨里 奈央",          photo: "tomisato_nao" , group: "nogizaka" },
    { en: "Nakanishi Aruno",          ja: "中西 アルノ",        photo: "nakanishi_aruno" , group: "nogizaka" },
    { en: "Atago Kokone",             ja: "愛宕 心響",          photo: "atago_kokone" , group: "nogizaka" },
    { en: "Okoshi Hinano",            ja: "大越 ひなの",        photo: "okoshi_hinano" , group: "nogizaka" },
    { en: "Ozu Reina",                ja: "小津 玲奈",          photo: "ozu_reina" , group: "nogizaka" },
    { en: "Kaibe Akari",              ja: "海邉 朱莉",          photo: "kaibe_akari" , group: "nogizaka" },
    { en: "Kawabata Hina",            ja: "川端 晃菜",          photo: "kawabata_hina" , group: "nogizaka" },
    { en: "Suzuki Yuuna",             ja: "鈴木 佑捺",          photo: "suzuki_yuuna" , group: "nogizaka" },
    { en: "Setoguchi Mitsuki",        ja: "瀬戸口 心月",        photo: "setoguchi_mitsuki" , group: "nogizaka" },
    { en: "Nagashima Rio",            ja: "長嶋 凛桜",          photo: "nagashima_rio" , group: "nogizaka" },
    { en: "Masuda Mirine",            ja: "増田 三莉音",        photo: "masuda_mirine" , group: "nogizaka" },
    { en: "Morihira Urumi",           ja: "森平 麗心",          photo: "morihira_urumi" , group: "nogizaka" },
    { en: "Yada Moeka",               ja: "矢田 萌華",          photo: "yada_moeka" , group: "nogizaka" },
  ],
  hinatazaka: [
    { en: "Kanemura Miku",    ja: "金村 美玖",   photo: "kanemura_miku" , group: "hinatazaka" },
    { en: "Kosaka Nao",       ja: "小坂 菜緒",   photo: "kosaka_nao" , group: "hinatazaka" },
    { en: "Kamimura Hinano",  ja: "上村 ひなの", photo: "kamimura_hinano" , group: "hinatazaka" },
    { en: "Takahashi Mikuni", ja: "髙橋 未来虹", photo: "takahashi_mikuni" , group: "hinatazaka" },
    { en: "Morimoto Marie",   ja: "森本 茉莉",   photo: "morimoto_marie" , group: "hinatazaka" },
    { en: "Yamaguchi Haruyo", ja: "山口 陽世",   photo: "yamaguchi_haruyo" , group: "hinatazaka" },
    { en: "Ishizuka Tamaki",  ja: "石塚 瑶季",   photo: "ishizuka_tamaki" , group: "hinatazaka" },
    { en: "Konishi Nanami",   ja: "小西 夏菜実", photo: "konishi_nanami" , group: "hinatazaka" },
    { en: "Shimizu Rio",      ja: "清水 理央",   photo: "shimizu_rio" , group: "hinatazaka" },
    { en: "Shogenji Yoko",    ja: "正源司 陽子", photo: "shogenji_yoko" , group: "hinatazaka" },
    { en: "Takeuchi Kirari",  ja: "竹内 希来里", photo: "takeuchi_kiraki" , group: "hinatazaka" },
    { en: "Hirao Honoka",     ja: "平尾 帆夏",   photo: "hirao_honoka" , group: "hinatazaka" },
    { en: "Hiraoka Mitsuki",  ja: "平岡 海月",   photo: "hiraoka_mitsuki" , group: "hinatazaka" },
    { en: "Fujishima Kaho",   ja: "藤嶌 果歩",   photo: "fujishima_kaho" , group: "hinatazaka" },
    { en: "Miyachi Sumire",   ja: "宮地 すみれ", photo: "miyachi_sumire" , group: "hinatazaka" },
    { en: "Yamashita Haruka", ja: "山下 葉留花", photo: "yamashita_haruka" , group: "hinatazaka" },
    { en: "Watanabe Rina",    ja: "渡辺 莉奈",   photo: "watanabe_rina" , group: "hinatazaka" },
    { en: "Ota Mizuki",       ja: "大田 美月",   photo: "ota_mizuki" , group: "hinatazaka" },
    { en: "Ono Manami",       ja: "大野 愛実",   photo: "ono_manami" , group: "hinatazaka" },
    { en: "Katayama Saki",    ja: "片山 紗希",   photo: "katamaya_saki" , group: "hinatazaka" },
    { en: "Kuramori Hinano",  ja: "蔵盛 妃那乃", photo: "kuramori_hinano" , group: "hinatazaka" },
    { en: "Sakai Nina",       ja: "坂井 新奈",   photo: "saki_nina" , group: "hinatazaka" },
    { en: "Sato Yu",          ja: "佐藤 優羽",   photo: "sato_yu" , group: "hinatazaka" },
    { en: "Shimoda Izuki",    ja: "下田 衣珠季", photo: "shimoda_izuki" , group: "hinatazaka" },
    { en: "Takai Rika",       ja: "高井 俐香",   photo: "takai_rika" , group: "hinatazaka" },
    { en: "Tsurusaki Niko",   ja: "鶴崎 仁香",   photo: "tsurusaki_niko" , group: "hinatazaka" },
    { en: "Matsuo Sakura",    ja: "松尾 桜",     photo: "matsuo_sakura" , group: "hinatazaka" },
  ],
};

export const GROUP_LABELS = {
  sakurazaka: { en: "Sakurazaka46", ja: "櫻坂46" },
  nogizaka:   { en: "Nogizaka46",   ja: "乃木坂46" },
  hinatazaka: { en: "Hinatazaka46", ja: "日向坂46" },
};

// Returns the public path for a member's default photo
// member must have both .photo (filename) and .group (sakurazaka/nogizaka/hinatazaka)
export function getDefaultPhoto(member) {
  if (!member?.photo || !member?.group) return null;
  const folderMap = { sakurazaka: "sakurazaka46", nogizaka: "nogizaka46", hinatazaka: "hinatazaka46" };
  const folder = folderMap[member.group] || member.group;
  return `/miiguri-scheduler/members/${folder}/${member.photo}.jpg`;
}
