export const MEMBERS = {
  sakurazaka: [
    { en: "Endo Hikari", ja: "遠藤 光莉" },
    { en: "Ozono Rei", ja: "大園 玲" },
    { en: "Onuma Akiho", ja: "大沼 晶保" },
    { en: "Kousaka Marino", ja: "幸阪 茉里乃" },
    { en: "Takemoto Yui", ja: "武元 唯衣" },
    { en: "Tamura Hono", ja: "田村 保乃" },
    { en: "Fujiyoshi Karin", ja: "藤吉 夏鈴" },
    { en: "Masumoto Kira", ja: "増本 綺良" },
    { en: "Matsuda Rina", ja: "松田 里奈" },
    { en: "Morita Hikaru", ja: "森田 ひかる" },
    { en: "Moriya Rena", ja: "守屋 麗奈" },
    { en: "Yamazaki Ten", ja: "山﨑 天" },
    { en: "Ishimori Rika", ja: "石森 璃花" },
    { en: "Endo Riko", ja: "遠藤 理子" },
    { en: "Odakura Reina", ja: "小田倉 麗奈" },
    { en: "Kojima Nagisa", ja: "小島 凪紗" },
    { en: "Taniguchi Airi", ja: "谷口 愛季" },
    { en: "Nakashima Yuzuki", ja: "中嶋 優月" },
    { en: "Matono Mio", ja: "的野 美青" },
    { en: "Mukai Itoha", ja: "向井 純葉" },
    { en: "Murai Yu", ja: "村井 優" },
    { en: "Murayama Miu", ja: "村山 美羽" },
    { en: "Yamashita Shizuki", ja: "山下 瞳月" },
    { en: "Asai Konomi", ja: "浅井 恋乃未" },
    { en: "Inaguma Hina", ja: "稲熊 ひな" },
    { en: "Katsumata Haru", ja: "勝又 春" },
    { en: "Sato Neo", ja: "佐藤 愛桜" },
    { en: "Nakagawa Chihiro", ja: "中川 智尋" },
    { en: "Matsumoto Wako", ja: "松本 和子" },
    { en: "Meguro Hiiro", ja: "目黒 陽色" },
    { en: "Yamakawa Ui", ja: "山川 宇衣" },
    { en: "Yamada Momomi", ja: "山田 桃実" },
  ],
  nogizaka: [
    { en: "Ito Riria", ja: "伊藤 理々杏" },
    { en: "Iwamoto Renka", ja: "岩本 蓮加" },
    { en: "Yoshida Ayano Christie", ja: "吉田 綾乃クリスティ" },
    { en: "Endo Sakura", ja: "遠藤 さくら" },
    { en: "Kaki Haruka", ja: "賀喜 遥香" },
    { en: "Kanagawa Saya", ja: "金川 紗耶" },
    { en: "Kuromi Haruka", ja: "黒見 明香" },
    { en: "Shibata Yuna", ja: "柴田 柚菜" },
    { en: "Tamura Mayu", ja: "田村 真佑" },
    { en: "Tsutsui Ayame", ja: "筒井 あやめ" },
    { en: "Hayashi Runa", ja: "林 瑠奈" },
    { en: "Yumiki Nao", ja: "弓木 奈於" },
    { en: "Ioki Mao", ja: "五百城 茉央" },
    { en: "Ikeda Teresa", ja: "池田 瑛紗" },
    { en: "Ichinose Miku", ja: "一ノ瀬 美空" },
    { en: "Inoue Nagi", ja: "井上 和" },
    { en: "Okamoto Hina", ja: "岡本 姫奈" },
    { en: "Ogawa Aya", ja: "小川 彩" },
    { en: "Okuda Iroha", ja: "奥田 いろは" },
    { en: "Kawasaki Sakura", ja: "川﨑 桜" },
    { en: "Sugawara Satsuki", ja: "菅原 咲月" },
    { en: "Tomisato Nao", ja: "冨里 奈央" },
    { en: "Nakanishi Aruno", ja: "中西 アルノ" },
    { en: "Atago Kokone", ja: "愛宕 心響" },
    { en: "Okoshi Hinano", ja: "大越 ひなの" },
    { en: "Ozu Reina", ja: "小津 玲奈" },
    { en: "Kaibe Akari", ja: "海邉 朱莉" },
    { en: "Kawabata Hina", ja: "川端 晃菜" },
    { en: "Suzuki Yuuna", ja: "鈴木 佑捺" },
    { en: "Setoguchi Mitsuki", ja: "瀬戸口 心月" },
    { en: "Nagashima Rio", ja: "長嶋 凛桜" },
    { en: "Masuda Mirine", ja: "増田 三莉音" },
    { en: "Morihira Urumi", ja: "森平 麗心" },
    { en: "Yada Moeka", ja: "矢田 萌華" },
  ],
  hinatazaka: [
    { en: "Kanemura Miku", ja: "金村 美玖" },
    { en: "Kosaka Nao", ja: "小坂 菜緒" },
    { en: "Kamimura Hinano", ja: "上村 ひなの" },
    { en: "Takahashi Mikuni", ja: "髙橋 未来虹" },
    { en: "Morimoto Marie", ja: "森本 茉莉" },
    { en: "Yamaguchi Haruyo", ja: "山口 陽世" },
    { en: "Ishizuka Tamaki", ja: "石塚 瑶季" },
    { en: "Konishi Nanami", ja: "小西 夏菜実" },
    { en: "Shimizu Rio", ja: "清水 理央" },
    { en: "Shogenji Yoko", ja: "正源司 陽子" },
    { en: "Takeuchi Kirari", ja: "竹内 希来里" },
    { en: "Hirao Honoka", ja: "平尾 帆夏" },
    { en: "Hiraoka Mitsuki", ja: "平岡 海月" },
    { en: "Fujishima Kaho", ja: "藤嶌 果歩" },
    { en: "Miyachi Sumire", ja: "宮地 すみれ" },
    { en: "Yamashita Haruka", ja: "山下 葉留花" },
    { en: "Watanabe Rina", ja: "渡辺 莉奈" },
    { en: "Ota Mizuki", ja: "大田 美月" },
    { en: "Ono Manami", ja: "大野 愛実" },
    { en: "Katayama Saki", ja: "片山 紗希" },
    { en: "Kuramori Hinano", ja: "蔵盛 妃那乃" },
    { en: "Sakai Nina", ja: "坂井 新奈" },
    { en: "Sato Yu", ja: "佐藤 優羽" },
    { en: "Shimoda Izuki", ja: "下田 衣珠季" },
    { en: "Takai Rika", ja: "高井 俐香" },
    { en: "Tsurusaki Niko", ja: "鶴崎 仁香" },
    { en: "Matsuo Sakura", ja: "松尾 桜" },
  ],
};

export const GROUP_LABELS = {
  sakurazaka: { en: "Sakurazaka46", ja: "櫻坂46" },
  nogizaka: { en: "Nogizaka46", ja: "乃木坂46" },
  hinatazaka: { en: "Hinatazaka46", ja: "日向坂46" },
};
